name: action-name
on:
  pull_request:
     branches: [master]
     types: [ labeled ]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'test')
    name: build-name
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hola Mundo"


